version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/nitish_checkList:1"
        LoadBalancerInfo:
          ContainerName: "nitish_checkList"
          ContainerPort: "8200"
        PlatformVersion: "LATEST"