version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/nitish_severity:1"
        LoadBalancerInfo:
          ContainerName: "nitish_Severity"
          ContainerPort: "8300"
        PlatformVersion: "LATEST"